name: Format (PHP)

on: [push, pull_request]

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              # with:
              #     ref: ${{ github.head_ref }}
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
            - name: Run php-cs-fixer
              run: ./vendor/bin/php-cs-fixer fix --config=.php_cs.dist --allow-risky=yes

            - uses: stefanzweifel/git-auto-commit-action@v4.1.0
              with:
                  commit_message: Apply php-cs-fixer changes
                  branch: ${{ github.head_ref }}
