name: Format (prettier)

on: [push, pull_request]

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install
              run: yarn install

            - name: Run prettier
              run: yarn run prettier --write 'resources/**/*.{css,js,vue}'

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply prettier changes
